### PR TITLE
The code.google.com repo isn't valid any more. Changed the protobuf to golang.org

### PR DESCRIPTION
**Pull request by indykish**
Changed from `code.google.com/p/goprotobuf/proto` to 
`github.com/golang/protobuf/proto`

### CODE REVIEW

**Comment by indykish** [comment]
@mrb  Are you going to take a look on this pullrequest ?

**Comment by mrb** [comment]
@indykish Are you using riakpbc in production? Are you interested in helping with ongoing maintenance?

**Comment by indykish** [comment]
@mrb  Yes we use it on staging, and will go to prod, shortly,  would be glad to give you a hand.

**Comment by mrb** [comment]
@indykish You are now a collaborator! Have fun.

**Pull request merged**
